version: '3.8'

services:
  postgresdb:
    image: 'postgres:latest'
    container_name: dbsales_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    container_name: redis_container
    image: 'redis:alpine'
    ports:
    - "${REDIS_PORT}:6379"

  redisinsight:
    container_name: redisinsight_container
    image: 'redislabs/redisinsight:latest'
    ports:
      - '8001:8001'




