version: '3.5'

services:
  postgres:
    container_name: dbsales_container
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${process.env.POSTGRES_DB}
      POSTGRES_USER: ${process.env.POSTGRES_USER}
      POSTGRES_PASSWORD: ${process.env.POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${process.env.POSTGRES_PORT}:5432"

  redis:
    container_name: redis_container
    image: 'redis:alpine'
    ports:
      - "${process.env.REDIS_PORT}:6379"

  redisinsight:
    container_name: redisinsight_container
    image: 'redislabs/redisinsight:latest'
    ports:
      - "8001:8001"


